# Generated by Django 4.2.3 on 2023-07-09 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('869513da-134a-4885-bc6b-5f5360c278bf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
