# Generated by Django 4.2.3 on 2023-07-09 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_id_employee_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('bc449cf8-9985-46bd-8c24-31602e379495'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
