# Generated by Django 4.2.3 on 2023-07-10 01:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_uid'),
        ('employee', '0004_alter_employee_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('53af3ce1-a192-4c46-b5b0-de6ea583ea35'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
