# Generated by Django 4.2.3 on 2023-07-10 02:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_uid'),
        ('employee', '0006_alter_employee_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('fef94db4-50b3-4ef7-9446-6a4bbd09c627'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
