# Generated by Django 4.2.3 on 2023-07-10 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_company_alter_employee_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3f1e4e2c-3474-411e-993b-d1bf9ab562a5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
