# Generated by Django 4.2.3 on 2023-07-10 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d8ffe5f7-fc87-4b46-b78d-9572661d7e8d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
