# Generated by Django 4.2.3 on 2023-07-10 03:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employee_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9ace49e0-a976-4468-95ba-9a902b4c524c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
