# Generated by Django 4.2.3 on 2023-07-09 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d0ccef57-877f-4e36-806d-fe94ddb84793'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
