# Generated by Django 4.2.3 on 2023-07-10 01:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d755f1fc-cdad-46c9-9bf3-afa6e7e4e183'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
