# Generated by Django 4.2.3 on 2023-07-10 02:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('2cc58093-45ab-4b98-8ba2-f2c2496fdcd4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
