# Generated by Django 4.2.3 on 2023-07-10 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_company_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f19e2512-a6cc-4adb-9136-797ddb1abbb1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
