# Generated by Django 4.2.3 on 2023-07-10 03:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8fce683b-97a2-4062-830e-2f4087b98ba1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
