# Generated by Django 4.2.3 on 2023-07-09 22:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Log',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('4fe4ebd8-28de-4df3-9adc-2e7cfe62e80b'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('woring', models.BooleanField(default=True)),
                ('checked_out_date', models.DateTimeField(auto_now_add=True)),
                ('checked_out_condition', models.CharField(max_length=50)),
                ('returned_date', models.DateTimeField(auto_now_add=True)),
                ('returened_condition', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
            options={
                'verbose_name_plural': 'Device_Logs',
                'ordering': ['device'],
            },
        ),
    ]
