# Generated by Django 4.2.3 on 2023-07-09 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device_log', '0002_alter_device_log_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_log',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3f05fa3f-2efe-4204-ab26-9561a14c2974'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
