# Generated by Django 4.2.3 on 2023-07-10 01:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device_log', '0003_alter_device_log_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_log',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('75496718-2770-480e-ada0-35492229670a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
