# Generated by Django 4.2.3 on 2023-07-10 02:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device_log', '0005_alter_device_log_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_log',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a0810286-9c90-43a5-8073-d3d9c1794e15'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
