# Generated by Django 4.2.3 on 2023-07-10 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device_log', '0007_alter_device_log_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_log',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6cc6184a-6516-4691-afff-44b78f7367a8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
