# Generated by Django 4.2.3 on 2023-07-10 03:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_employee_uid'),
        ('device_log', '0008_alter_device_log_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_log',
            old_name='woring',
            new_name='working',
        ),
        migrations.AddField(
            model_name='device_log',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='device_log',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('60f34fcb-1c1f-4280-bbb5-5718d3646d99'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
