# Generated by Django 4.2.3 on 2023-07-09 22:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_alter_employee_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('a2a88696-de12-4465-b049-4f5226bee18d'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('check_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Devices',
                'ordering': ['name'],
            },
        ),
    ]
