# Generated by Django 4.2.3 on 2023-07-09 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('91fb18fb-5606-4353-a3c4-767d1044e8d3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
