# Generated by Django 4.2.3 on 2023-07-10 01:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_company_alter_employee_uid'),
        ('device', '0003_alter_device_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1229e342-a2e9-49eb-8686-1eff0a591e3a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
