# Generated by Django 4.2.3 on 2023-07-10 02:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_company_alter_employee_uid'),
        ('device', '0005_alter_device_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('45e64431-fb33-4d97-a905-a01dc7e2c395'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
