# Generated by Django 4.2.3 on 2023-07-10 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_alter_device_belongs_to_alter_device_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0eb29f56-5d8c-48f4-bc9f-89e7320ae363'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
